spring.application.name=api

# ==========================================
# CONEXÃO COM O BANCO DE DADOS (SUPABASE)
# ==========================================
# A URL segue o formato: jdbc:postgresql://<HOST>:<PORTA>/<DATABASE>
spring.datasource.url=jdbc:postgresql://db.zlglbuujxnegidzwfojo.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=P0Tl29eWpJqXNDsZ
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
# "update": Cria ou atualiza as tabelas no banco de dados automaticamente com base nas classes Java (@Entity)
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do VS Code os comandos SQL reais sendo executados pelo Spring
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true